### ISSUE TITLE
Create video tutorial of how to use the pipeline.

### ISSUE THREAD

**Issue by bkingery** [byu-animation/byu-animation-tools#40]
A screen recording of someone pushing the buttons.  Then record an explanation of it.

**Comment by nstandif** [comment]
VLC has a screencasting feature that may be useful.

**Comment by crydalch** [comment]
Not sure how things have changed since I left, but _gtk-recordmydesktop_ used to be installed. If you use it, you have to enable **Full Shots at Every Frame**, or it will only record near the mouse when using Houdini/Maya.

Talk to the sysadmin to get it installed if it's not on there; really useful little tool!
