### ISSUE TITLE
ownaya & owndini should be in the repo, with links in the main dir

### ISSUE THREAD

**Issue by ebrayton** [byu-animation/byu-animation-tools#76]
We ran into an issue when modellers tried to use check-out and check-in this morning. Maya shelf dir variable had changed and there's no way from the repo to change the script all of the modellers had copied from the main owned directory. Making those links in the main dir alleviates two problems:
- users copying the ownaya script will get a link instead of a copy
- we can change the script within the repo

**Comment by bkingery** [comment]
I changed this so that hopefully this will never happen again.

The ownaya and owndini scripts now do this
cd /groups/owned/byu-animation-tools/
runs the managed project script  (ie: sh project_maya.sh)
cd -

This means that if we ever update the project_*.sh scripts the scripts that the users are running should always be "up-to-date"
