### ISSUE TITLE
Deleting A Digital Asset that a Container Depends on, breaks the container

### ISSUE THREAD

**Issue by nstandif** [byu-animation/byu-animation-tools#81]

**Comment by bkingery** [comment]
A possible solution is to create a dependency database and not allow assets to be delete if they are referenced by another.
This should be done on checkin

**Comment by eestrada** [comment]
Another way to attack it would be to parse the various HDA definitions and ask each asset what it contains _when the delete tool is run_. [This Python method](http://www.sidefx.com/docs/houdini12.1/hom/hou/Node#children) does most of the work for us. It would be more expensive per use of the delete tool, but we wouldn't have to worry about maintaining a database.

Also, I would like to avoid using opaque file formats outside the otl files themselves. This is why I like that the Maya check in/out just uses hidden [plain text files](http://www.faqs.org/docs/artu/ch05s01.html). If this brute force methodology is acceptably fast, I would prefer it over having another database.

Any other ideas on ways to solve the problem?

**Comment by bkingery** [comment]
My initial thought is that node.children() function should be sufficient.  I like it a lot.  I'll be in tomorrow and can give it a test to see how slow it is, but I don't think it will be a problem at all.

I can already see the code in my head.  It should be a pretty elegant solution.

**Comment by bkingery** [comment]
It turns out this is extremely slow, as you have to create an instance of every node...
This is especially a problem if someone has done something dumb with a shader that make is take a year to load.
If there was a way to list the children without creating an instance that would be ideal.

**Comment by eestrada** [comment]
Yeah, I noticed that when looking at the API. Another way to approach this is to inspect the sections of the assets. We can do that in one of two ways. First, we can use [hou.hda.expandToDirectory()](http://www.sidefx.com/docs/houdini12.1/hom/hou/hda) and search the asset sections as a file hierarchy. Or (probably faster to compute) use [hou.HDADefinition.sections()](http://www.sidefx.com/docs/houdini12.1/hom/hou/HDADefinition#sections) to inspect the sections directly. I am figuring out now which section holds the definition of the child nodes of an asset. I'll post again once I have figured it out.

**Comment by eestrada** [comment]
Ok, figured it out! Here is the Python code to get what we are looking for:

`typedefinition.sections()['CreateScript'].contents()`

The contents() method returns just a plain old string containing hscript commands separated by newlines (and it returns super crazy fast since it isn't actually creating the node). Every time the creation script adds a new node it contains the following on a new line:

`opadd -e -n nodeType nodeInstanceName`

Thus we can simply parse for any lines starting with `oppadd` and throw out the rest (since all they are doing is setting specific parameters and whatnot). Then we can check for the first white space delimited token after the `opadd -e -n` and that should be the node type.

How did I figure it al out? [By the power of Grayskull!](http://youtu.be/7yeA7a0uS3A?t=21s)

**Comment by eestrada** [comment]
We could also use the above method on check in to make sure no one is creating shaders using the `material shader builder`  shop node (which seems to be the root of the super slow node creation problems).

**Comment by bkingery** [comment]
Fixed by merge #87
